/**
 * Git Live Mode - Push results to remote and create PR
 *
 * This module handles pushing E2B sandbox execution results directly
 * to a remote feature branch and creating a pull request, bypassing
 * the default download workflow.
 */

import type { Sandbox } from 'e2b';
import type { Logger } from '../logger.js';

/**
 * Options for git live push and PR creation
 */
export interface GitLiveOptions {
  repoPath: string;
  targetBranch: string;
  featureBranch?: string;
  prompt: string;
  executionTime: number;
  sessionId: string;
  sandboxId: string;
  githubToken: string;
}

/**
 * Result of git live operation
 */
export interface GitLiveResult {
  success: boolean;
  branchName: string;
  prUrl?: string;
  targetBranch: string;
  error?: string;
}

/**
 * Generate feature branch name from prompt
 *
 * @param prompt - User's execution prompt
 * @returns Slugified branch name with timestamp
 */
export function generateBranchName(prompt: string): string {
  // Slugify: lowercase, replace non-alphanumeric with hyphens
  const slug = prompt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') // Remove leading/trailing hyphens
    .substring(0, 50); // Limit to 50 chars

  // Add timestamp for uniqueness
  const timestamp = Date.now();
  return `e2b/${slug}-${timestamp}`;
}

/**
 * Generate PR body with execution details
 *
 * @param options - Git live options
 * @returns Formatted PR description
 */
export function generatePRBody(options: GitLiveOptions): string {
  const executionTimeFormatted = (options.executionTime / 1000).toFixed(1);

  return `# E2B Autonomous Execution

**Prompt:** ${options.prompt}

**Execution Details:**
- Execution Time: ${executionTimeFormatted}s
- Session ID: ${options.sessionId}
- Sandbox ID: ${options.sandboxId}
- Target Branch: ${options.targetBranch}

## Changes Summary

This PR contains the results of an autonomous E2B sandbox execution. The changes were generated automatically by Claude Code running in an isolated sandbox environment.

## Review Checklist

- [ ] Review all changed files
- [ ] Run tests locally
- [ ] Verify no sensitive data was committed
- [ ] Check for any unintended changes
- [ ] Validate the implementation meets requirements

<details>
<summary>E2B Execution Log</summary>

This PR was created automatically by \`parallel-cc sandbox-run --git-live\`.

**Session Information:**
- Session ID: \`${options.sessionId}\`
- Sandbox ID: \`${options.sandboxId}\`
- Execution completed in ${executionTimeFormatted} seconds

</details>

---

*Generated by [parallel-cc](https://github.com/frankbria/parallel-cc) E2B Sandbox Integration*`;
}

/**
 * Push results to remote feature branch and create pull request
 *
 * @param sandbox - E2B sandbox instance
 * @param logger - Logger instance
 * @param options - Git live options
 * @returns Result with branch name and PR URL
 */
export async function pushToRemoteAndCreatePR(
  sandbox: Sandbox,
  logger: Logger,
  options: GitLiveOptions
): Promise<GitLiveResult> {
  try {
    logger.info('Starting git live push and PR creation');

    // 1. Generate branch name if not provided
    const branchName = options.featureBranch || generateBranchName(options.prompt);
    logger.info(`Using branch name: ${branchName}`);

    // 2. Create and checkout feature branch
    logger.info('Creating feature branch in sandbox');
    const checkoutResult = await sandbox.commands.run(`git checkout -b ${branchName}`, {
      cwd: '/workspace',
      timeoutMs: 10000
    });

    if (checkoutResult.exitCode !== 0) {
      throw new Error(`Failed to create branch: exit code ${checkoutResult.exitCode}`);
    }

    // 3. Stage all changes
    logger.info('Staging changes');
    const addResult = await sandbox.commands.run('git add .', {
      cwd: '/workspace',
      timeoutMs: 30000
    });

    if (addResult.exitCode !== 0) {
      throw new Error(`Failed to stage changes: exit code ${addResult.exitCode}`);
    }

    // 4. Commit with descriptive message
    logger.info('Creating commit');
    const commitMessage = `E2B execution: ${options.prompt}

Autonomous execution completed in ${(options.executionTime / 1000).toFixed(1)}s

Session: ${options.sessionId}
Sandbox: ${options.sandboxId}`;

    const commitResult = await sandbox.commands.run(`git commit -m "${commitMessage.replace(/"/g, '\\"')}"`, {
      cwd: '/workspace',
      timeoutMs: 10000
    });

    if (commitResult.exitCode !== 0) {
      throw new Error(`Failed to commit: exit code ${commitResult.exitCode}`);
    }

    // 5. Push to remote
    logger.info('Pushing to remote');
    const pushResult = await sandbox.commands.run(`git push -u origin ${branchName}`, {
      cwd: '/workspace',
      timeoutMs: 60000
    });

    if (pushResult.exitCode !== 0) {
      throw new Error(`Failed to push to remote: exit code ${pushResult.exitCode}`);
    }

    // 6. Create PR using gh CLI
    logger.info('Creating pull request');
    const prTitle = `E2B: ${options.prompt}`;
    const prBody = generatePRBody(options);

    // Escape single quotes for shell
    const escapedTitle = prTitle.replace(/'/g, "'\\''");
    const escapedBody = prBody.replace(/'/g, "'\\''");

    const ghResult = await sandbox.commands.run(
      `GITHUB_TOKEN=${options.githubToken} gh pr create --title '${escapedTitle}' --body '${escapedBody}' --base ${options.targetBranch}`,
      {
        cwd: '/workspace',
        timeoutMs: 30000
      }
    );

    if (ghResult.exitCode !== 0) {
      throw new Error(`Failed to create PR: exit code ${ghResult.exitCode}`);
    }

    // 7. Parse PR URL from output
    // gh pr create outputs the PR URL as the last line
    const prUrl = ghResult.stdout?.trim().split('\n').pop() || undefined;

    logger.info(`PR created successfully: ${prUrl}`);

    return {
      success: true,
      branchName,
      prUrl,
      targetBranch: options.targetBranch
    };
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    logger.error(`Git live failed: ${errorMsg}`);

    return {
      success: false,
      branchName: options.featureBranch || 'unknown',
      targetBranch: options.targetBranch,
      error: errorMsg
    };
  }
}
